services:
    jarobe.task_runner.driver_factory:
        class: Jarobe\TaskRunnerBundle\Driver\Factory\DriverFactory
        arguments:
            - ''
        public: false

    jarobe.task_runner.hydrator:
        class: Jarobe\TaskRunnerBundle\Hydrator\Hydrator
        arguments:
            - '@jarobe.task_runner.registry'
        public: false

    jarobe.task_runner.processor:
        class: Jarobe\TaskRunnerBundle\Processor\Processor
        arguments:
            - '@jarobe.task_runner.driver_factory'
        public: false

    jarobe.task_runner.discovery:
        class: Jarobe\TaskRunnerBundle\Hydrator\Discovery
        arguments:
          - '%jarobe.task_runner.types.namespace%'
          - '%jarobe.task_runner.types.directory%'
          - 'kernel.root_dir%'
        public: false

    jarobe.task_runner.registry:
        class: Jarobe\TaskRunnerBundle\Hydrator\Registry
        arguments:
          - '@jarobe.task_runner.discovery'
        public: false

    jarobe.task_runner.task_event_manager:
        class: Jarobe\TaskRunnerBundle\Manager\TaskEventManager
        arguments:
            - '@doctrine.orm.report_entity_manager'
        public: true

    jarobe.task_runner.task_manager:
        class: Jarobe\TaskRunnerBundle\Manager\TaskManager
        arguments:
            - '@jarobe.task_runner.task_event_manager'
            - '@jarobe.task_runner.hydrator'
            - '@jarobe.task_runner.processor'
        public: true