build:
    tests:
        override:
            -
                command: 'vendor/bin/phpunit --coverage-clover=build/unit_coverage.xml'
                coverage:
                    file: 'build/unit_coverage.xml'
                    format: 'clover'

filter:
    excluded_paths:
        - "vendor/"
        - "Tests/"

checks:
    php:
        code_rating: true
        duplication: true

